import dynamic from 'next/dynamic'
import type { Metadata } from 'next'
import '@fontsource/m-plus-rounded-1c'
import { Inter } from 'next/font/google'
import './globals.css'
import { Topbar } from '@/components/topbar/topbar'
import { LanguageProvider } from '@/contexts/languageContext'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Guilherme Caramori - Developer',
  description: 'Generated by create next app',
}

const Computer = dynamic(() =>
  import('../components/computer/computer').then((mod) => mod.Computer)
)

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <LanguageProvider>
      <html lang="en">
        <body
          className={`relative flex flex-col justify-center items-start ${inter.variable} bg-linear-to-tr from-[var(--background)] to-[var(--background-gradient)] antialiased`}
        >
          <Topbar />

          <Computer />

          {children}
        </body>
      </html>
    </LanguageProvider>
  )
}
