import { Suspense } from 'react'
import type { Metadata } from 'next'
import '@fontsource/m-plus-rounded-1c'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/sidebar/sidebar'
import { LanguageProvider } from '@/contexts/languageContext'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Guilherme Caramori - Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <LanguageProvider>
      <html lang="en">
        <body
          className={`flex ${inter.variable} bg-gradient-to-b from-[var(--background)] to-[var(--background-gradient)] antialiased`}
        >
          <Suspense>
            <Sidebar />

            {children}
          </Suspense>
        </body>
      </html>
    </LanguageProvider>
  )
}
